List<Sweet> sweets = [
  Sweet(
    name: 'Bounty',
    description: 'Кокосовая начинка в молочном шоколаде.',
    imageUrl: 'https://media.istockphoto.com/id/183745191/ru/фото/bounty-кокосового-шоколада.jpg?s=612x612&w=0&k=20&c=CGPjeMPiORjSJEgC_oA2bCbbMW6MObuXTuc-_H_KeIA=',
    price: 60,
    brand: 'Mars',
    flavor: 'Шоколад с кокосом',
    ingredients: 'Шоколад, кокосовая стружка, сахар',
  ),
  Sweet(
    name: 'Alpen Gold',
    description: 'Молочный шоколад с лесными орехами и изюмом.',
    imageUrl: 'https://media.istockphoto.com/id/539951548/ru/фото/алпен-gold-шоколад.jpg?s=612x612&w=0&k=20&c=0IRraQtT-X7xnC5AaVvmoPmZ5OxF_f9-Wqfnwf5jfLU=',
    price: 80,
    brand: 'Alpen Gold',
    flavor: 'Молочный шоколад с орехами и изюмом',
    ingredients: 'Шоколад, орехи, изюм, сахар',
  ),
  Sweet(
    name: 'Mars',
    description: 'Шоколадный батончик с нугой и карамелью.',
    imageUrl: 'https://media.istockphoto.com/id/1212156476/ru/фото/mars-шоколадный-батончик.jpg?s=612x612&w=0&k=20&c=tF14BvB3ePUAjssQ6p5D0YZUcaDboOfszHbFkfR6v7c=',
    price: 55,
    brand: 'Mars',
    flavor: 'Шоколад с нугой и карамелью',
    ingredients: 'Шоколад, карамель, нуга, сахар',
  ),
  Sweet(
    name: 'Raffaello',
    description: 'Конфеты с миндалем и кокосовой стружкой.',
    imageUrl: 'https://media.istockphoto.com/id/492964242/ru/фото/рафаэлло-изолированные-на-белом-фоне.jpg?s=612x612&w=0&k=20&c=dJK34oyRjQdH2Ky2GxlV-fXJd2iwYChM-M-xoVfp7yo=',
    price: 200,
    brand: 'Ferrero',
    flavor: 'Кокос и миндаль',
    ingredients: 'Миндаль, кокосовая стружка, сахар',
  ),
  Sweet(
    name: 'Milky Way',
    description: 'Шоколадный батончик с воздушной начинкой.',
    imageUrl: 'https://media.istockphoto.com/id/1212156517/ru/фото/milky-way-шоколадный-батончик.jpg?s=612x612&w=0&k=20&c=_SKqeA58xwEPZfPBMRi3H6DoEE6fw8d5wzpjF_HWBbs=',
    price: 50,
    brand: 'Mars',
    flavor: 'Шоколад с воздушной начинкой',
    ingredients: 'Шоколад, нуга, сахар, молоко',
  ),
  Sweet(
    name: 'Merci',
    description: 'Ассорти шоколадных конфет с разными начинками.',
    imageUrl: 'https://media.istockphoto.com/id/515399899/ru/фото/merci-шоколад-ассорти.jpg?s=612x612&w=0&k=20&c=gy4gHHfnywquFTu5PjNd6rTfBbMGY1YvwvDJ8Y0zR-Q=',
    price: 250,
    brand: 'Merci',
    flavor: 'Разные виды шоколада',
    ingredients: 'Шоколад, карамель, орехи, сливки',
  ),
  Sweet(
    name: 'Hershey\'s',
    description: 'Американский шоколад с молочным вкусом.',
    imageUrl: 'https://media.istockphoto.com/id/1047187802/ru/фото/hersheys-молочный-шоколад.jpg?s=612x612&w=0&k=20&c=jF46y0mQlmdvCvZL27pu_X1uCjoL-rARZTzgSzGRWtU=',
    price: 110,
    brand: 'Hershey\'s',
    flavor: 'Молочный шоколад',
    ingredients: 'Какао, молоко, сахар, ваниль',
  ),
  Sweet(
    name: 'Chupa Chups',
    description: 'Леденцы на палочке с различными вкусами.',
    imageUrl: 'https://media.istockphoto.com/id/512034348/ru/фото/чупа-чупс.jpg?s=612x612&w=0&k=20&c=ayFS6A5kNjAzz6dnMKpBy8gHVJBNNZ-nJTuDfgXxbIY=',
    price: 20,
    brand: 'Chupa Chups',
    flavor: 'Фрукты',
    ingredients: 'Сахар, фруктовые ароматизаторы, красители',
  ),
  Sweet(
    name: 'Twirls',
    description: 'Шоколадные вафли в молочном шоколаде.',
    imageUrl: 'https://media.istockphoto.com/id/1183872522/ru/фото/twirls-шоколад.jpg?s=612x612&w=0&k=20&c=lEgms5CO0EXjIcBeTQABjFub1QQE-59OfoRA1hFVdwA=',
    price: 60,
    brand: 'Cadbury',
    flavor: 'Шоколад с вафлями',
    ingredients: 'Шоколад, вафли, сахар, молоко',
  ),
  Sweet(
    name: 'Haribo',
    description: 'Мармеладные мишки с фруктовыми вкусами.',
    imageUrl: 'https://media.istockphoto.com/id/464349973/ru/фото/haribo-золотые-медведи.jpg?s=612x612&w=0&k=20&c=Jsl8o-1pjQeS0IqW6Bbce6ZcVf3gxdN6wrz-NryKwIY=',
    price: 80,
    brand: 'Haribo',
    flavor: 'Фрукты',
    ingredients: 'Сахар, фруктовые ароматизаторы, желатин',
  ),
];